
# data paths
CPIS_2000_shp_path: 'data/raw/CPIS/World_CPIS_2000.shp' # from https://github.com/DetectCPIS/global_cpis_shp; see readme for details
CPIS_2021_shp_path: 'data/raw/CPIS/World_CPIS_2021.shp' # from https://github.com/DetectCPIS/global_cpis_shp; see readme for details
Africa_countries_shp_path: 'data/raw/Africa_Boundaries-shp/Africa_Boundaries.shp' # from https://hub.arcgis.com/datasets/07610d73964e4d39ab62c4245d548625/explore
Africa_CPIS_2000_shp_path: 'data/raw/CPIS/Africa_CPIS_2000.shp' # same as CPIS_2000_shp_path but filtered to Africa
Africa_CPIS_2021_shp_path: 'data/raw/CPIS/Africa_CPIS_2021.shp' # same as CPIS_2021_shp_path but filtered to Africa
government_effectiveness_path: 'data/raw/government_effectiveness/government_effectiveness.csv' # from https://data.worldbank.org/indicator/GE.EST. Renamed and header removed
SPEI_12_path: 'data/raw/SPEI_drought/spei12.nc' # from https://data.ceda.ac.uk/neodc/spei_africa/data. This one is at a 12 month scale.